services:
  postgres:
    image: postgres:16
    container_name: nexocore_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexocore_db
    ports:
      - "5433:5432"
    volumes:
      - nexocore_postgres_data:/var/lib/postgresql/data

volumes:
  nexocore_postgres_data: